# conda
name: mkRisk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - pip
  - pip:
    - pip-tools
    - ipynb==0.5.1
    #- orjson
    #- mxnet~=1.7 #maxima version compatible con windows. la version de request debe ser maximo 2.19.0 y yfinace debe tener 0.20.0 como minimo.
    #- gluonts
    - yfinance
    - plotly==5.15.0  
    - cufflinks  
    - beautifulsoup4==4.12.2
    - selenium==4.10.0
  - pandas=1.2.2
  - numpy==1.19.2
  - ipykernel
  - gdal=3.2.2
  - fiona=1.8.19
  - geopandas==0.9.0
  - nbformat
  - openpyxl==3.0.6
  - pyxlsb==1.0.9